services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
      - MYSQL_DATABASE=email_ms
      - MYSQL_ROOT_PASSWORD=123456789
